#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4548B3A8C0D70C12 (john@szakmeister.net)
#
Name     : deprecated-nose
Version  : 1.3.7
Release  : 53
URL      : http://pypi.debian.net/nose/nose-1.3.7.tar.gz
Source0  : http://pypi.debian.net/nose/nose-1.3.7.tar.gz
Source99 : http://pypi.debian.net/nose/nose-1.3.7.tar.gz.asc
Summary  : nose extends unittest to make testing easier
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: deprecated-nose-bin = %{version}-%{release}
Requires: deprecated-nose-man = %{version}-%{release}
Requires: deprecated-nose-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-core
BuildRequires : setuptools-legacypython
Patch1: doc-install.patch

%description
Basic usage
***********
Use the nosetests script (after installation by setuptools):

%package bin
Summary: bin components for the deprecated-nose package.
Group: Binaries

%description bin
bin components for the deprecated-nose package.


%package extras
Summary: extras components for the deprecated-nose package.
Group: Default

%description extras
extras components for the deprecated-nose package.


%package legacypython
Summary: legacypython components for the deprecated-nose package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-nose package.


%package man
Summary: man components for the deprecated-nose package.
Group: Default

%description man
man components for the deprecated-nose package.


%package python
Summary: python components for the deprecated-nose package.
Group: Default

%description python
python components for the deprecated-nose package.


%prep
%setup -q -n nose-1.3.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554341102
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/nosetests
%exclude /usr/bin/nosetests-2.7

%files extras
%defattr(-,root,root,-)
/usr/bin/nosetests-2.7

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man1/nosetests.1

%files python
%defattr(-,root,root,-)
